[package]
name = "jsonrpc"
version = "0.9.0"
authors = ["Andrew Poelstra <apoelstra@wpsoftware.net>"]
license = "CC0-1.0"
homepage = "https://github.com/apoelstra/rust-jsonrpc/"
repository = "https://github.com/apoelstra/rust-jsonrpc/"
documentation = "https://www.wpsoftware.net/rustdoc/jsonrpc/"
description = "Rust support for the JSON-RPC 2.0 protocol"
keywords = [ "protocol", "json", "http", "jsonrpc" ]
readme	 = "README.md"

[lib]
name = "jsonrpc"
path = "src/lib.rs"

[dependencies]
serde = "1"
serde_derive = "1"
serde_json = "1"

[dependencies.hyper]
version = "0.9"
default-features = false

[features]
default = []
ssl = ["hyper/ssl"]
